# Generated by Django 3.2 on 2021-05-15 03:49

import auth_.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos', validators=[auth_.utils.validators.validate_size, auth_.utils.validators.validate_extension]),
        ),
    ]
