# Generated by Django 3.2 on 2021-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='departure_at',
            field=models.DateTimeField(verbose_name='Дата вылета'),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='airline',
            field=models.CharField(max_length=32, verbose_name='Авиакомпания'),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='arrival_at',
            field=models.DateTimeField(verbose_name='Дата прилета'),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='departure_at',
            field=models.DateTimeField(verbose_name='Дата вылета'),
        ),
    ]
