# Generated by Django 3.2 on 2021-04-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0002_auto_20210425_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultitem',
            name='destination',
            field=models.CharField(default='NQZ', max_length=3, verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='origin',
            field=models.CharField(default='ALA', max_length=3, verbose_name='Откуда'),
        ),
    ]
