# Generated by Django 3.2 on 2021-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0003_auto_20210425_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresultitem',
            name='currency',
            field=models.CharField(default='KZT', max_length=3, verbose_name='Валюта'),
        ),
    ]
