# Generated by Django 3.2 on 2021-04-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0004_alter_searchresultitem_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='departure_at',
            field=models.DateField(verbose_name='Дата вылета'),
        ),
    ]
