# Generated by Django 3.2 on 2021-05-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airflow', '0006_farefamily_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchResultItem',
            new_name='Offer',
        ),
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
