# Generated by Django 3.2 on 2021-05-10 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.IntegerField(choices=[(1, 'MASTER_CARD'), (2, 'VISA')], default=0)),
                ('card_number', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя Фамилия')),
                ('expired_at', models.CharField(max_length=5, verbose_name='Годен до')),
                ('cvv', models.IntegerField(verbose_name='CVV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Банковская карта',
                'verbose_name_plural': 'Банковские карты',
            },
        ),
    ]
