# Generated by Django 3.2 on 2021-05-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_bankcard_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcard',
            old_name='expired_at',
            new_name='expires_at',
        ),
    ]
