# Generated by Django 3.2 on 2021-05-14 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet', '0003_rename_expired_at_bankcard_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcard',
            options={},
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='card_type',
            field=models.IntegerField(choices=[(1, 'MASTER_CARD'), (2, 'VISA')], default=0, verbose_name='Тип карты'),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('date_of_birth', models.DateField(verbose_name='Дата рожения')),
                ('citizenship', models.CharField(max_length=255, verbose_name='Гражданство')),
                ('document_number', models.CharField(max_length=255, verbose_name='Номер документа')),
                ('expires_at', models.DateField(null=True, verbose_name='Дата истечения документа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
